### ISSUE TITLE
Color Picker Desktop 

### ISSUE THREAD

**Issue by Bboy486** [MattsShack/Plex-Movie-Poster-Display#35]
Sorry for all the bugs but the color doesn't work. I can't change from default (yellow) or when I type F in the field it auto-populated #000000

https://www.awesomescreenshot.com/video/2831556?key=c2837d78babdf576d06d280944068751

**Comment by ZeroCoolGOS** [comment]
No worries.  That is what bug reporting is for.

Yes, we have been aware of this issue.

I have been working to sort this issue out but have not been successful as of yet, and had not had gotten around to write up the issue myself.

Thank you for logging this.  I will be continuing to work on trying to fix this up.

In the mean time you should be able to copy/past values into the field.  Yes, this is a bad workaround.
If you just google "hex color picker" you will be able to get the hex value you can copy/paste into that field.

The reason that it is "auto filling" is because the color picker actually is working, its just stuck behind the background.

**Comment by ZeroCoolGOS** [comment]
A new color picker function should be available in v2.9.2

**Comment by ZeroCoolGOS** [comment]
@Bboy486 

If this is working as per your needs then we should be able to close this ticket.

**Comment by titelies** [comment]
Most color pickers I have tried worked fine yesterday and today. The Progress Bar Color picker, however only works with a copy & paste into the field box, doesn't allow to manually typed in. Thank you for work on this project, version 3 is impressive. Have been using PMPD since January 2017.

**Comment by ZeroCoolGOS** [comment]
I will have a look at the color picker for the progress bar as well.

**Comment by ZeroCoolGOS** [comment]
@titelies 

Thank you for bringing this one to my attention and I have now fixed it in the v2.9.3 build once @MattsShack approves my Pull Request.

**Comment by ZeroCoolGOS** [comment]
@Bboy486 

If this is now working for you we can now close this ticket. 😃

**Comment by Bboy486** [comment]
Close this one. I commented in the other thread.
