### ISSUE TITLE
Remove all Plex Asset

### ISSUE THREAD

**Issue by MattsShack** [MattsShack/Plex-Movie-Poster-Display#38]
I have been made _aware_ that PMPD is in direct violation of the [PLEX trademarks and guidelines](https://www.plex.tv/about/privacy-legal/plex-trademarks-and-guidelines/). I would like to apologize to PLEX for these violations.  All development will be focused on bringing this project into compliance with the PLEX Trademarks and Guidelines.

**Example Violations:** 
You may not:
Use Plex or derivatives thereof in the name of your application

You may not:
Copy the Plex look and feel of any Plex web site (including the use of our distinct color combinations, graphic designs or typography) or create any altered, distorted or interpreted representation of any of the Plex marks, as this could create confusion among our users.

**To-Do:**
New frontend with unique code and color scheme.
Audit all code to make sure there is no other trademark / copyright infringements.
Possible new name for project.

**Comment by ZeroCoolGOS** [comment]
@MattsShack 

I am sorry that I had made the changes to the admin UI that caused this confusion as well.

What can I do to help clear up the code for this?

I will go though the admin pages and work on addressing all the issues that are in violation.

**Comment by MattsShack** [comment]
It okay, we live and learn. 

I am not sure on the color scheme yet. I am open to suggestions.

Once the color scheme is decided work can begin on a new, built from scratch, bootstrap(?) frontend. It can keep all the same poster display features, however absolutely no PLEX scripts, CSS, HTML, etc. can be used.

This started as a side project and I am so surprised / happy that others are interest in using it... much less helping with development.

**Comment by ZeroCoolGOS** [comment]
When you say not PLEX scripts. What do you mean by that?  Are we still able to keep using the API?

It feels like the violation is more on the cosmetic level.

I can help work on rewriting the admin interfaces since it was me who did most of the rewrite in the first place. 

I had been working on moving all "Plex" related logic into its own library so this may be a good time to continue to move that logic around.  None of that logic is Plex proprietary.

If we build it in such a way we should be able to "change" themes in and some needs change.

**Comment by ZeroCoolGOS** [comment]
Also what would you like to call the project?

Do we still want to call it Poster Display?  What had you envisioned this to grow into?

I have been looking at this project as a digital kiosk, and could grow into something outside of Plex, but keep that as a base.  Possibly even having it for other media applications or for even photos.

**Comment by ZeroCoolGOS** [comment]
As you think of what direction you would like to take the project.  Give me through the weekend to work on a cleaner version of the settings pages. 

I will work on stripping any Plex images and links. 

Removing pointers to the CSS file.  There looks like a bunch of CSS that we may not need.  I have also identified a few areas that can be improved anyways.

I will have it in my forked branch and will tag this ticket when I do my commits.  You are more then welcome to pull my branch and review the progress as I go so that we stay on the same page. 

Once we stream lined the css files then it should be easier to apply your custom designed theme faster.

**Comment by MattsShack** [comment]
Yes, as long as the projects stays within the term it can use the Plex API, webhooks, etc. 

Still working on the color scheme / name options. Suggestions are always welcome.

I would like the project to be compatible other streaming platforms in the future (Example Jellyfin / Emby); as well as have the ability to display art and photos. Maybe a more modular design.

**Comment by MattsShack** [comment]
**Update**
Still working on a layout, name, etc.

**Layout**
Looking at using the latest Bootstrap and Bootstrap Icons. [Terms](https://themes.getbootstrap.com/terms/)

**Color Scheme**
Still open to suggestions / ideas.
![Capture](https://user-images.githubusercontent.com/597565/108912217-f438e380-75ed-11eb-9ef1-4aaf3d4b7ead.JPG)

```
HEX       Example Usage 
#222831   Background
#393E46   Hover
#00ADB5   Button
#EEEEEE   Text
```

**Comment by ZeroCoolGOS** [comment]
Ok, cool.

Did you want to keep a similar type of layout? as in the sections on the left side and the main in the right?

As long as we are not using any of the css, fonts and colors I think the flow should still be safe to use.

I have a bunch of ideas to optimize but without using alot of 3rd party resources.

**Comment by ZeroCoolGOS** [comment]
@MattsShack 

I am pretty close to having all the css cleaned up for the settings page.

Do you have a new font in mind?

I have been using your above colors but I have taken some liberties with them just for testing purposes.

I am hoping to have this cleared up by the end of the weekend.  That should clear up most of the color/icon/style issues.

Let me know if you have any more info as to what you would like changed or see, or any directions you would like to take.

**Comment by ZeroCoolGOS** [comment]
@MattsShack 

I believe I now should be complete with the decoupling of the PLEX branding inside of the setting.

I have been trying to isolate what is "PLEX" and what is "Movie Poster Display".  If you run my latest branch you will see that I am testing out any settings for a "PLEX" server into its own page.  That way we could add different types of Media servers going forward.

**Comment by MattsShack** [comment]
Thank you. I will check it out soon as I am back at home.

**Comment by ZeroCoolGOS** [comment]
Sure, no problem.

I will have a few more code drops in the next day or two for your consideration and hope to have a v2.10 PR with these changes within the next few days so we can get to an "Unblocked" state and then I can do some polish as I fix up more of the bugs that have been popping up and back to working on features.

**Comment by ZeroCoolGOS** [comment]
All Plex images are now removed.

PLEX CSS file still exists but will be removed in next commit.

To-Do:
New frontend with unique code and color scheme.
- Frontend has been refactored and 90% of the CSS has either been renamed & changed formatting, some of the "css classes" are stock classes so no copywrite infringement should be clamed.  More refactoring can and will be done for simplification. 
- Skeleton structure remains but changed as not specific to PLEX.
- Home icon has also been changed to a generic "home"
- Most colors have been set as per the above.

Audit all code to make sure there is no other trademark / copyright infringements.
- Frontend display no longer displays "Plex Movie Poster Display"; currently stripped down to "Movie Poster Display"
- Only reference that remains to PLEX is there is a "Plex Configuration Page", and this page is the only location that PLEX settings would be set.  It also includes the PLEX copywrite footer.

Possible new name for project.
- Current placeholder name has been set to "Movie Poster Display"

Outstanding Items:
- Final "first pass" of CSS cleanup
- Review if Config.php values need to be modified and change from using "pmp" - Possible change for V3 as that would be more of a breaking change, the majority of the changes currently have been cosmetic to preserve backwards compatibility.
- Once name has been decided the "plexmovieposter" folder can be renamed and pointers adjusted
- A font for the Setting to be selected
- Proper complete documentation in the ChangeLog.

Notes:
- I have refrained from using 3rd party assets such as BootStrap as much as I can so that we contain more control and use stock functionality so we don't have to worry about any potential terms conflicts.

**Comment by ZeroCoolGOS** [comment]
@MattsShack 

Any more thoughts on font or colors?

I still have tweaks to make in the backend.

What other changes would you like to see?

**Comment by MattsShack** [comment]
Sorry, I am still reviewing. Let me get back to you this week. Thank you for all the hard work.

-Matt

**Comment by ZeroCoolGOS** [comment]
No worries.

I have a few more changes coming in the next few days.

**Comment by ZeroCoolGOS** [comment]
Hey @MattsShack 

Sorry I have been MIA for the past few weeks.  I just started a new job and been spending all my time at that.

Have you had a chance to see what new changes you are looking for so we can look at closing this ticket?

I hope to jump back on the project in the next few weeks and hope to help clear up the backlog of issues that we have to a much smaller amount by the summer.

**Comment by MattsShack** [comment]
@ZeroCoolGOS Welcome back. :)
Congratulations on the new job!
