### ISSUE TITLE
Mobile Friendly PMPD3 Suggestion

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#40]
One of the features I liked about PMPD2 was the ability to manage/edit the PMPD settings easily from a mobile device if need be. I know some things are being changed due to Plex branding, a mobile friendly version of PMPD3 would be a suggestion that I believe would be beneficial to some users. https://i.imgur.com/hisNQPsl.png

**Comment by ZeroCoolGOS** [comment]
@titelies 

I like the idea, but one of the things that I believe we are facing is that there are now so many options, and that is why we split it up into multiple pages.

Are there any options that you would be mostly wanting to control on a mobile device (vs all of them)?

That way we could prioritize them as a POC.

And yes, due to the rebranding I don't know when this issue will be able to be tackled next.  Hopefully in the next month or two for starters.

**Comment by titelies** [comment]
No worries, and excellent point... this does have much more options. Thank you for your updates. Hoping my suggestions will be worthwhile to other PMPD users. Kudos!
