### ISSUE TITLE
502 Bad Gateway Nginx Error

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#43]
Can anyone provide as to why I'd be getting an 502 Bad Gateway Nginx 1.14.2 error message for the following pages:
Coming Soon, Now Showing, Custom Configuration, and Font Configuration?
I can access General, Security, Common, Server and Client Configuration pages without issue.
Issued seems to have occurred when I was uploading one of the custom fonts on the Font Configuration page.
Any advice would be greatly appreciated. Copying the directories and files into the /var/www/html/ did not help with the issue.

**Comment by ZeroCoolGOS** [comment]
This sounds like you are missing files when you updated. 

Can you check to see if all the files are copied over correctly?

Also what build are you running?

**Comment by titelies** [comment]
Pulled 2.9.3 last night and copied to the /var/www/html folder and it was working last night and this morning. I was uploading the Mr Robot TV Show font on the Font Configuration page and it seemed to fail and then those 4 bottom pages from the left menu began reporting the 502 Bad Gateway error. Tried recopying new folders and files into the html folder as mentioned and it didn't help. Rebooted Pi, cleared cached and cookies on my browser with no luck.

**Comment by ZeroCoolGOS** [comment]
Hmm. That is odd. 

I will try and do that on my side and see if I can reproduce the error.

**Comment by titelies** [comment]
I had uploaded quite a few fonts to the folder without issue but when I tried to upload that one it seemed to have broken something.
I did use ApplePiBaker to make a backup of my SD Card while everything was working and I have the Config file backed up thanks to that feature in the General page, so I will give that a try later this evening.

**Comment by ZeroCoolGOS** [comment]
I have pulled down the Mr Robot font zip from FamFonts.

I am not able to recreate the 502 bad gateway issue.  But unfortunately this font will not work at this time as we only support the ttf font format and this font package only contains otf font file.

Please write up a separate bug for support of multiple font formats and some examples so we can explore them in the future.

But since I am not able to solve this issue by recreating it, try and remove the "__MACOSX" and the "mr-robot" folders to see if that resolves the issue so you don't have to do a restore.

the fonts are stored in the cache/fonts folder.

**Comment by titelies** [comment]
That did the trick... I deleted the __MACOSX folder and rebooted and I am able to access those pages again! Outstanding! 
Thank you very much!!! Didn't end up needing the restore. Kudos Geoff!

**Comment by ZeroCoolGOS** [comment]
Cool.  I'm glad that worked out.

I will add "Remove _MACOSX folder" to the next round of enhancements for the font ticket I have created.
