### ISSUE TITLE
Coming Soon Show Movies - Recently Added & Newest TV Show Poster/Backgrounds Issue

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#45]
I tend to use ALL in the Show Movies Coming Soon Advanced dropdown menu cause Plex seems to always have the wrong info for Recently Added and Newest, old movies get mistakenly added, not sure if others have noticed this as well. 
However, the issue that I'm reporting is when I tested the Recently Added and Newest dropdown choices, instead of PMPD displaying the TV Show posters, it posts random background images that I didn't select for my TV Shows... weird! Show Movies: Unwatched and All display TV Show posters correctly but the bottom 2 choices from the dropdown menu show random incorrect background images as seen in these screenshots:
https://i.imgur.com/A2gGxGJ.jpg
https://i.imgur.com/0UWUa6E.jpg
https://i.imgur.com/35ka0UL.jpg

**Comment by ZeroCoolGOS** [comment]
Interesting.

I have not actually tested the other options, so that is my bad. 

I will have a look this week and see what is going on.

**Comment by titelies** [comment]
No worries Geoff, just trying to help. Upon further investigation, the images showing up for Recently Added & Newest are Episode Posters, not TV Show posters.

**Comment by ZeroCoolGOS** [comment]
Ah.  Yes, I see what your saying.

All and Unwatched seem to be working correctly, but when you select Newest or Recently Added then you get the TV show episode art.

I will dig in the logs now and see what I can find.

*** Update ***
I have found out why it's showing the "Episode Poster" when set to Newest or Recently added.
It has to do with the metadata coming back from the API.

Now that I know what the issue is I will work on building a fix for this.

**Comment by ZeroCoolGOS** [comment]
@titelies 

When displaying posters for TV shows.  Would you always want to use the TV Show proper poster or would you also want the option to set for the "episode poster" or "season poster"?

**Comment by titelies** [comment]
> @titelies 
> 
> When displaying posters for TV shows.  Would you always want to use the TV Show proper poster or would you also want the option to set for the "episode poster" or "season poster"?

I would most likely use the TV Show poster but the Season Poster sounds like be a nice option as well. Episode Poster would not work for my particular case cuz my TV is displayed vertically and the Episode posters are horizontal.

**Comment by ZeroCoolGOS** [comment]
Ok, cool.

I have found the issue and will have it fixed in my next push as well as add an option to set the type (Episode, Season, Series) just like how the Now Playing has that option.

The only thing I can see is when you use TV shows as part of your Coming Soon, the same poster can come up more often then others if you have added multiple episodes as the changes get a lot higher you will hit one of the episodes, but that should not be too big of an issue.

**Comment by titelies** [comment]
Thanks for the TV Show poster info, sounds like I'll be choosing the Season Posters to get some variation. Much appreciated!

**Comment by ZeroCoolGOS** [comment]
This fix should now be in v2.10.

Give it a go and let me know if its working correctly for you.

**Comment by titelies** [comment]
Working well in Show Media: Newest and have decided to go with the Seasons Poster... Great idea Geoff!

**Comment by titelies** [comment]
FYI: Successfully tested with new Plex TV Series (BETA) Agent

**Comment by ZeroCoolGOS** [comment]
Plex TV Services (BETA) agent?

**Comment by titelies** [comment]
Yep, just released for Plex Pass users in the past week: https://forums.plex.tv/t/beta-new-plex-tv-series-scanner/696242

**Comment by ZeroCoolGOS** [comment]
Interesting.  I will have to dig into that more.
