### ISSUE TITLE
Cache Images Enabled but Posters disappearing

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#58]
I have Cache Images enabled but it seems that posters automatically get removed after 24 hours.  I noticed that my poster statistics numbers sometimes go down... I don't need it to automatically remove them (64GB SD card), the clear cache button is a worthwhile option if I needed space.

**Comment by ZeroCoolGOS** [comment]
Yes, by design it does have a 24hr removal for cache images.

**Comment by titelies** [comment]
Are cached images beneficial to PMPD or not really? not sure why the 24 hour removal is necessary...

**Comment by ZeroCoolGOS** [comment]
@MattsShack can provide more information the caching and 24hr removal.

But from what I am to believe is that it is meant to help speed up the load on poor WIFI connections, so that a local copy is faster to load.

That being said.  The way I have it implemented is that its more of a client/server model so that I have one backend and running on multiple browsers on multiple devices.

**Comment by MattsShack** [comment]
@ZeroCoolGOS is correct. The cache image feature itself was meant to help with poor image loading over WIFI connections. 

The intent of the cache image 24 hour removal was to free up storage space on the SD card, as well as remove old images that my have been updated or changed in Plex.

**Comment by titelies** [comment]
Can that be set as optional or set to delete at a certain capacity? I have a 64GB card and would prefer to cache as many as possible... Just a thought! Thanks for the reply @MattsShack  Hope all is well with you!

**Comment by ZeroCoolGOS** [comment]
I can look at what it would take to allow for this to be an option.

**Comment by titelies** [comment]
Stellar!
