### ISSUE TITLE
Remove Cinema trailer and Movie pre-roll Image before Now Showing poster

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#81]
I have Plex Cinema Trailers and Movie pre-rolls enabled in the Plex Media Server > Extra setting.
When the trailer and pre-roll play before the movie starts, PMPD3 will display a horizontal background trailer/pre-roll image as seen in the screenshots below. Is there a way to not display those in PMPD3? In PMPD2, it would continue to show Coming Soon posters until the actual film started playing and then the Now Showing poster would display, it would not show images for trailers or movie pre-rolls.
https://i.imgur.com/A2gGxGJ.jpg
https://i.imgur.com/0UWUa6E.jpg

**Comment by ZeroCoolGOS** [comment]
Is there a way?  No.
But it's something we can look into. 

It might be a bit tricky depending on what data is passed from PLEX.  Based on the data that is provided there is an isPlaying state and we pick up the metadata from that.

We will have to review and see the API provided and instead of continuing to show coming soon we may be able to jump to the now playing poster. That might be the easier approach but it may take a while to figure out.

**Comment by ZeroCoolGOS** [comment]
@titelies 

After some review of the code.  It does not look as complicated as I had expected.  I should be able to get this adjusted within the next release.

But, we wont be able to jump to the 'Now Playing' as I had hoped so it will just stay with the coming soon until the movie or show starts.

**Comment by titelies** [comment]
Thanks for another stellar fix @ZeroCoolGOS
