### ISSUE TITLE
Progress Bar not displaying correctly

### ISSUE THREAD

**Issue by ZeroCoolGOS** [MattsShack/Plex-Movie-Poster-Display#85]
Progress bar not displaying correctly if font size is too large.

**Comment by titelies** [comment]
@ZeroCoolGOS Hey Geoff, I think there may be an issue with the progress bar when playing a personal home video from Plex instead of a movie. I believe the bar and font are fine when playing a movie and the PMPD poster is displaying in portrait mode. However,  I quickly noticed the other day that the progress bar didn't run the full length of the TV display while in portrait mode and it also had an effect on the font size when I was watching one our vacation videos that I have in a Plex library. Not sure if it has to do with the home video posters being landscape, and not vertical like a movie poster. I will try to get you some sample images. Have been wrapped with a number of things for the past few weeks.

**Comment by ZeroCoolGOS** [comment]
@titelies 

Yes please, if you can get me some examples of the issue that would be great.  I made a few more changes to the progress bar in 2.12.1 (PR pending) as well so hopefully it was a one off.

**Comment by ZeroCoolGOS** [comment]
@titelies 

2.12.1 has been merged so ready to try.

**Comment by titelies** [comment]
Issue resolved with 2.12.1 @ZeroCoolGOS

**Comment by ZeroCoolGOS** [comment]
Sounds good. 

I was playing with the size of the progress bar and how it displayed. 

One idea was to only have it the length of the art but not sure if that would work out. 

I hope to offer a few more options with the progress bar, such as the start and end time.

I have also been looking at a different but similar project for other ideas as well. 

If you have more ideas on features or changes. Please let us know. :)
